name: jax-fem-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - meshio
  - mpich
  - hdf5
  - petsc=3.20.0
  - petsc4py=3.20.0
  - pip
  - jaxlib=*=*cpu*
  - jax
  - pip:
    - setuptools
    - wheel
    - gmsh==4.11.1
    - pyfiglet==1.0
    - fenics-ufl
    - pytest